version: '3.8'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  prism-neuro-backend:
    container_name: capital-remit-backend
    build:
      context: ./
      args:
        - no-cache
    ports:
      - '8000:4000'
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c 'npm run migration:deploy && npm run swagger && npm run dev:backend'

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: prism-neuro-db
